# fly.toml app configuration file generated for tj-iou on 2024-11-15T19:01:11-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tj-iou'
primary_region = 'ewr'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
MONGO_URI = "mongodb+srv://yoda:tbrtqOA0uPtLiAwn@cluster0.xidtdhg.mongodb.net/iou?retryWrites=true&w=majority&appName=Cluster0"